<a href="https://colab.research.google.com/github/dcolbourne/Colab/blob/TensorFlow/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow.

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using  GPUs with TensorFLow (or TPUs)
* Excerecises to try for yourself!


## Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of our vector
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]], dtype = tf.float16) # specify the data type with dtype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([[[10,7,3],
                       [3,7,9]],
                       [[5,6,7],
                        [10,11,16]],
                      [[5,9,7],
                       [16,78,65]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[10,  7,  3],
        [ 3,  7,  9]],

       [[ 5,  6,  7],
        [10, 11, 16]],

       [[ 5,  9,  7],
        [16, 78, 65]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind spreed and direction)
* Matrix: a 2-dimensional array of numbers* Tenso: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)


In [12]:
### Creating tensors with tf.Variable

In [13]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [15]:
changeable_tensor[0].assign(9)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [16]:
# unchangeable_tensor[0].assign(9)

In [17]:
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

### Creating random tensors
Random tensors are tensors of some arbitrary size that contain random numbers

In [18]:
# Create two random (but the same) tensors
random1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random1 = random1.normal(shape=(6,5))
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape=(6,5))
random1, random2, random1 == random2 # Are they equal?


(<tf.Tensor: shape=(6, 5), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
        [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284],
        [ 0.1480774 , -0.23362993, -0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
        [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 , -0.48293006],
        [-0.52447474, -1.0345329 ,  1.3066901 , -1.5184573 , -0.4585211 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(6, 5), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
        [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284],
        [ 0.1480774 , -0.23362993, -0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
        [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 , -0.48293006],
        [-0.52447474, -1.0345329 ,  1.3066901 , -1.5

### Shuffle the order of elements in a tensor

In [19]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim

2

In [20]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42)
shuffled = tf.random.shuffle(not_shuffled, seed = 42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [21]:
not_shuffled, shuffled, not_shuffled == shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [22]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled2 = tf.constant([[10,7,3],
                            [3,4,9],
                            [2,5,3]])

tf.random.set_seed(65) # global level random seed
tf.random.shuffle(not_shuffled2, seed = 69)   # operation level random seed



<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7,  3],
       [ 3,  4,  9],
       [ 2,  5,  3]], dtype=int32)>

 ### Other ways to make tensors

In [23]:
# Create a tensor of all ones

tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [24]:
# Create a tensor of all zeros

tf.zeros((16,4))

<tf.Tensor: shape=(16, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy into tensors
You can also turn NumPy arrays into tensors

In [25]:
import numpy as np

numpy_A = np.arange(1, 25, dtype = np.int32) # create a NumPy array between 1 and 25

# X = tf.constan(some matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-captial for vector

numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [26]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [27]:
A = tf.constant(numpy_A, shape = (2,3,4))
B = tf.constant(numpy_A)
C = tf.constant(numpy_A, shape = (3,8))
A, B, C

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

In [28]:
C.ndim


2

### Getting information from tensors

* Shape - tensor.shape
* Rank - tensor.ndim
* Axis or dimension - tensor[0], tensor{:,1]...
* Size - td.size(tensor)

Rank - The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.

In [29]:
tf.size(A)


<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [30]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [32]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [33]:
2 * 3 * 4 * 5

120

In [34]:
# Get various attributes of our tensor
print("Dataytpe of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements on the 0 axis:", rank_4_tensor.shape[0])
print("Elements on the last axis:", rank_4_tensor.shape[-1])
print("The total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Dataytpe of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements on the 0 axis: 2
Elements on the last axis: 5
The total number of elements in our tensor: 120


### Indexing tensors
Tensors can be indexed just like Python lists


In [35]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [36]:
# Get the first 2 elements of each dimension
rank_4_tensor, rank_4_tensor[:2,:2,:2,:2]

(<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
 array([[[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]],

In [37]:
# Get the first element from each dimension from each index except for the last one

rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [38]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],
                            [3,4]])
rank_2_tensor.ndim, rank_2_tensor.shape, rank_2_tensor



(2,
 TensorShape([2, 2]),
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [39]:
# Get the last item of each row of our rank t tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [40]:
# Add in an extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor.ndim

3

In [41]:
rank_3_tensor.shape

TensorShape([2, 2, 1])

In [42]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [43]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [44]:
tf.expand_dims(rank_2_tensor, axis = 0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [45]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [46]:
tf.expand_dims(rank_2_tensor, axis = 1) # expand the 01axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operations)
**Basic Operations**

In [47]:
# You can add values to a tensor using the addition operator

tensor2 = tf.constant([[10, 7], [3,4]])
tensor2 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [48]:
# Original tensor is unchanged

tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [49]:
# Multiplication also works
tensor2 * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [50]:
tensor2 - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [51]:
# We can use the tensorflow built-in function too
# This would run faster on a tensor training TPU than the basic operators

tf.multiply(tensor2, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [52]:
tf.math.divide(tensor2, 2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [53]:
tf.math.multiply(tensor2, 40)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 280],
       [120, 160]], dtype=int32)>

In [54]:
tf.divide(tensor2, 2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [55]:
tf.multiply(tensor2, tensor2)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [56]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[10,  7,  3],
        [ 3,  7,  9]],

       [[ 5,  6,  7],
        [10, 11, 16]],

       [[ 5,  9,  7],
        [16, 78, 65]]], dtype=int32)>

In [57]:
tf.math.multiply(tensor, tensor)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 100,   49,    9],
        [   9,   49,   81]],

       [[  25,   36,   49],
        [ 100,  121,  256]],

       [[  25,   81,   49],
        [ 256, 6084, 4225]]], dtype=int32)>

**Matrix Multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

There are two rules our tensors (or matrices) need the fulfill if we are going to multiply them:

1. The inner dimensions must match
2. the resulting matrix has the shape of the outer dimensions

In [58]:
# See https//:matrixmultiplication.xyz

In [59]:
# Matrix multiplication in TensorFlow - tf.linalg.matmul

print(tensor2)
tf.matmul(tensor2, tensor2)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [60]:
# Matrix multiplication with Python operator "@"
tensor2 @ tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [61]:
tensor4 = tf.constant([[[1,2,5],
                       [7,2,1],
                       [3,3,3]]])
tensor5 = tf.constant([[3,5],
                       [6,7],
                       [1,8]])
tensor4, tensor5

(<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
 array([[[1, 2, 5],
         [7, 2, 1],
         [3, 3, 3]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [62]:
tf.linalg.matmul(tensor4, tensor5)

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[20, 59],
        [34, 57],
        [30, 60]]], dtype=int32)>

In [63]:
# https://www.mathisfun.com/algebra/matrix-multiplying.html
# the number of columns in the first matrix must be the same of the rows in the second matrix
# 3X3 ---- 3X2  the inner dimensions match
# 2X3 ---- 2X3 the inner dimensions do not match, we cannot multiply them.


In [64]:
# Create a tensor (3, 2)
X= tf.constant([[1,2],
                 [3,4],
                 [5,6]])

Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [65]:
# tf.linalg.matmul(X, Y)

In [66]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [72]:
tf.reshape(Y, [2,3])

# Or we can write it tf.reshape(Y, shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [74]:
X.shape, tf.reshape(Y, shape = (2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [77]:
X @ tf.reshape(Y, shape = (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [78]:
# Try to multiple X by reshaped Y
tf.linalg.matmul(X, tf.reshape(Y, (2,3)))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [80]:
# Try changing the shape of X instead of Y
tf.linalg.matmul(tf.reshape(X, shape = (2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [83]:
tf.reshape(X, shape = (2,3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [84]:
# We can do the same with transpose

In [88]:
X, tf.transpose(X), tf.reshape(X, shape = (2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [91]:
# Try matrix multiplication with transpose rather than reshape
# Outcome will be different than above using reshape
tf.linalg.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:

* 'tf.linalg.matmul()'
* 'tf.tensordot()'
* '@'



In [92]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [96]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [97]:
# Perform matrix mulitplicaiton between X and Y transposed
tf.linalg.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [98]:
# Perform matrix mulitplicaiton between X and Y reshaped
tf.linalg.matmul(X, tf.reshape(Y, shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [111]:
# Check the values of Y, reshaped Y, and transposed Y
print("Normal Y:")
print(Y, "\n")
print("Reshaped Y:")
print(tf.reshape(Y, shape = (2,3)), "\n")
print("Transposed Y:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Reshaped Y:
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transposed Y:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [112]:
tf.linalg.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, when performing matrix multiplication on two tensors and one od the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplicaiton rules.

### Changing the data type of a tensor

In [120]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [122]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [125]:
# Change from float32 to float16 (reduced precision)
tf.cast(B, dtype = tf.float16)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [127]:
D = tf.cast(B, dtype = tf.float16)
D.dtype

tf.float16

In [132]:
E = tf.cast(C, dtype = tf.float32)
E.dtype, E

(tf.float32,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>)

In [134]:
E_float16 = tf.cast(E, dtype = tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating Tensors