<a href="https://colab.research.google.com/github/dcolbourne/Colab/blob/TensorFlow/TFFundExercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### TensorFlow Fundamental Exercises


In [2]:
import tensorflow as tf

In [3]:
# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

vector_1 = tf.random.uniform(shape=[1], minval=0, maxval=25)
vector_1, vector_1.ndim

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([14.555976], dtype=float32)>,
 1)

Scalar

Definition: A scalar is a single numerical value. It has no direction or dimensions.
Example: Temperature (e.g., 25 degrees Celsius) or mass (e.g., 10 kg).
Vector

Definition: A vector is a one-dimensional array of numbers, which can represent a quantity that has both magnitude and direction.
Notation: Often represented as  
v
=
[
v
1
,
v
2
,
…
,
v
n
]
 .
Example: Velocity (e.g., 60 km/h to the north) or a force (e.g., 10 N at an angle).
Matrix

Definition: A matrix is a two-dimensional array of numbers, organized in rows and columns.
Notation: Typically represented as  
A
=
(
a
11
a
12
a
21
a
22
)
 .
Example: A transformation matrix in linear algebra or a data table with rows representing different observations and columns representing different variables.
Tensor

Definition: A tensor is a multi-dimensional generalization of scalars, vectors, and matrices. Tensors can have any number of dimensions (also called ranks).
Notation: A tensor can be represented as  
T
i
1
i
2
…
i
n
 , where  
i
1
,
i
2
,
…
,
i
n
  index the dimensions.
Example: A 3D tensor could represent the RGB color values of an image, where each pixel has three color channels (red, green, blue).
Summary

Scalar: 0D (single value).
Vector: 1D (array of values).
Matrix: 2D (array of values organized in rows and columns).
Tensor: nD (generalization of scalars, vectors, and matrices).

In [4]:
vector_2 = tf.constant([1,2,3,4,5])
vector_2

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [5]:
vector_1.dtype, vector_2.shape, vector_2.ndim

(tf.float32, TensorShape([5]), 1)

In [6]:
scalar_1 =tf.constant(1)
scalar_1

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
scalar_1.dtype, scalar_1.shape, scalar_1.ndim

(tf.int32, TensorShape([]), 0)

In [8]:
Matrix_1 = tf.constant([[1,2],[3,4]])
Matrix_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [9]:
Matrix_1.dtype, Matrix_1.shape, Matrix_1.ndim

(tf.int32, TensorShape([2, 2]), 2)

In [10]:
tensor_1 = tf.constant([[[1,2],[3,4]],[[4,5],[5,6]]])
tensor_1

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [5, 6]]], dtype=int32)>

In [11]:
tensor_1.dtype, tensor_1.shape, tensor_1.ndim

(tf.int32, TensorShape([2, 2, 2]), 3)

In [12]:
# 2. Find the shape, rank, and size of the tensors created in 1


In [13]:
vector_1.shape, tf.rank(vector_1), tf.size(vector_1)

(TensorShape([1]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [14]:
scalar_1.shape, tf.rank(scalar_1), tf.size(scalar_1)

(TensorShape([]),
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [15]:
Matrix_1.shape, tf.rank(Matrix_1), tf.size(Matrix_1)

(TensorShape([2, 2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [16]:
tensor_1.shape, tf.rank(tensor_1), tf.size(tensor_1)

(TensorShape([2, 2, 2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [17]:
# 3 Create two tensors containing random values between 0 and 1 with shape [5,300]

tensor_2 = tf.random.uniform(shape = [5,300], minval=0, maxval=1)

tensor_3 = tf.random.uniform(shape = [5,300], minval=0, maxval=1)

tensor_2, tensor_3

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.3840071 , 0.819281  , 0.9943638 , ..., 0.04706609, 0.7734312 ,
         0.53552806],
        [0.22466123, 0.8971895 , 0.76166   , ..., 0.47852147, 0.5238277 ,
         0.7964239 ],
        [0.30995452, 0.4967996 , 0.45913756, ..., 0.5601436 , 0.7004179 ,
         0.94215846],
        [0.4216919 , 0.32739305, 0.57523453, ..., 0.8093033 , 0.08450186,
         0.07517076],
        [0.35338306, 0.87372005, 0.69817555, ..., 0.303864  , 0.8260374 ,
         0.2370348 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.04490769, 0.24131167, 0.5739844 , ..., 0.5856122 , 0.24334943,
         0.60325766],
        [0.49590743, 0.281901  , 0.42589462, ..., 0.5568234 , 0.6786443 ,
         0.16218936],
        [0.96173   , 0.12748086, 0.29475892, ..., 0.19731891, 0.8622116 ,
         0.00629914],
        [0.43618333, 0.7511157 , 0.4339664 , ..., 0.9039768 , 0.9285008 ,
         0.4505148 ],
        [0.28661

In [26]:
# 4.Multiply the two sensors you created in 3 using matrix multiplication
tf.linalg.matmul(tensor_2, tf.transpose(tensor_3))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.84636 , 73.55881 , 67.79257 , 75.21025 , 74.879814],
       [76.26132 , 76.91911 , 72.12543 , 78.73442 , 78.25084 ],
       [77.81265 , 78.42283 , 71.31287 , 78.03071 , 77.464584],
       [77.202774, 78.58699 , 74.0576  , 79.53933 , 78.156586],
       [73.72766 , 76.43826 , 70.27637 , 74.21005 , 74.54742 ]],
      dtype=float32)>

In [19]:
tensor_3.dtype

tf.float32

In [29]:
# 5.Multiply the two sensors you created in 3 using dot product.

tf.tensordot(tensor_2, tf.transpose(tensor_3), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.84636 , 73.55881 , 67.79257 , 75.21025 , 74.879814],
       [76.26132 , 76.91911 , 72.12543 , 78.73442 , 78.25084 ],
       [77.81265 , 78.42283 , 71.31287 , 78.03071 , 77.464584],
       [77.202774, 78.58699 , 74.0576  , 79.53933 , 78.156586],
       [73.72766 , 76.43826 , 70.27637 , 74.21005 , 74.54742 ]],
      dtype=float32)>

In [30]:
# 6.Create a tensor with random values between 0 and 1 with shape [224, 224, 3]


In [38]:
tf.random.set_seed(42)
tensor_5 = tf.random.uniform(shape = [224, 224, 3], minval=0, maxval=1)
tensor_5

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        ...,
        [0.42612267, 0.09686017, 0.16105258],
        [0.1487099 , 0.04513884, 0.9497483 ],
        [0.4393103 , 0.28527975, 0.96971095]],

       [[0.73308516, 0.5657046 , 0.33238935],
        [0.8838178 , 0.87544763, 0.56711245],
        [0.8879347 , 0.47661996, 0.42041814],
        ...,
        [0.7716515 , 0.9116473 , 0.3229897 ],
        [0.43050945, 0.83253574, 0.45549798],
        [0.29816985, 0.9639522 , 0.3316357 ]],

       [[0.41132426, 0.2179662 , 0.53570235],
        [0.5112119 , 0.6484759 , 0.8894886 ],
        [0.42459428, 0.20189774, 0.85781324],
        ...,
        [0.02888799, 0.3995477 , 0.11355484],
        [0.68524575, 0.04945195, 0.17778492],
        [0.97627187, 0.79811585, 0.9411576 ]],

       ...,

       [[0.9019445 , 0.27011132, 0.8090267 ],
        [0.32

In [72]:
# 7.Find the min and max values of the tensor you created in 6 along the first axis.
tf.math.reduce_min(tensor_5), tf.math.reduce_max(tensor_5)

(<tf.Tensor: shape=(), dtype=float32, numpy=3.5762787e-07>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.999998>)

In [76]:
# 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]

tf.random.set_seed(42)
sq_tensor = tf.random.uniform(shape= (1,224,224,3))
sq_tensor.shape

TensorShape([1, 224, 224, 3])

In [78]:
sq2_tensor = tf.squeeze(sq_tensor)
sq2_tensor.shape

TensorShape([224, 224, 3])

In [114]:
# 9.Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor_6 = tf.constant([0,1,2,3,4,5,6,7,16,9])
tensor_6, tensor_6.shape

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7, 16,  9], dtype=int32)>,
 TensorShape([10]))

In [115]:
max_value = tf.argmax(tensor_6)

print(f'The indices where the vaule is maximum: {max_value}')
print(f'The maximum value was: {tensor_6[max_value]}')

The indices where the vaule is maximum: 8
The maximum value was: 16


In [117]:
import numpy as np
# tf.one_hot(np.array(tensor_6), depth=16)
tf.one_hot(tf.cast(tensor_6, dtype = tf.int32), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>